version: '3'
services:
    db:
        container_name: db_project
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db_data:/usr/data
        ports:
            - 3309:3306
    web:
        container_name: php_web_project
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 83:80
        depends_on: 
            - db
        links:
            - db
    phpmyadmin:
        container_name: phpmyadmin_project
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 8083:80
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
    db_data:
    src: